version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cricket-auction-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount database file for persistence (create if doesn't exist)
      - auction_db:/app/auction.db
      # Mount logs
      - ./backend/logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite:///./auction.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cricket-auction-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cricket-auction-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cricket-auction-network

networks:
  cricket-auction-network:
    driver: bridge

volumes:
  auction_db:
    driver: local

